"asmFish\fasm.exe" "asmFish\asmFishW_base.asm"      -m 50000 "Windows\Deep_asmFishW_%DATE%_base.exe"
"asmFish\fasm.exe" "asmFish\asmFishW_popcnt.asm"    -m 50000 "Windows\Deep_asmFishW_%DATE%_popcnt.exe"
"asmFish\fasm.exe" "asmFish\asmFishW_bmi2.asm"      -m 50000 "Windows\Deep_asmFishW_%DATE%_bmi2.exe"
"asmFish\fasm.exe" "asmFish\pedantFishW_base.asm"   -m 50000 "Windows\Deep_pedantFishW_%DATE%_base.exe"
"asmFish\fasm.exe" "asmFish\pedantFishW_popcnt.asm" -m 50000 "Windows\Deep_pedantFishW_%DATE%_popcnt.exe"
"asmFish\fasm.exe" "asmFish\pedantFishW_bmi2.asm"   -m 50000 "Windows\Deep_pedantFishW_%DATE%_bmi2.exe"
"asmFish\fasm.exe" "asmFish\asmFishL_base.asm"      -m 50000 "Linux\Deep_asmFishL_%DATE%_base"
"asmFish\fasm.exe" "asmFish\asmFishL_popcnt.asm"    -m 50000 "Linux\Deep_asmFishL_%DATE%_popcnt"
"asmFish\fasm.exe" "asmFish\asmFishL_bmi2.asm"      -m 50000 "Linux\Deep_asmFishL_%DATE%_bmi2"
"asmFish\fasm.exe" "asmFish\pedantFishL_base.asm"   -m 50000 "Linux\Deep_pedantFishL_%DATE%_base"
"asmFish\fasm.exe" "asmFish\pedantFishL_popcnt.asm" -m 50000 "Linux\Deep_pedantFishL_%DATE%_popcnt"
"asmFish\fasm.exe" "asmFish\pedantFishL_bmi2.asm"   -m 50000 "Linux\Deep_pedantFishL_%DATE%_bmi2"
pause
